name = "sub-box"
main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
ADMIN_USERNAME = "nas"
ADMIN_PASSWORD = "N1gh7f@ll99!"
JWT_SECRET = "iB}MMO,MB]OCh&!hxB_s[Jl6Q$TA+e=p,U6UxZ8,]L+]BV}:s?UF<f*WoKALeKpD"
SESSION_TAG = "0"
SESSION_DURATION = "2592000"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "subhome"
database_id   = "5f97046c-574c-40b2-b174-0da960786d03"

[observability.logs]
enabled = true
